name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
          
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imagengerald:v1.0
    - name: Correr imagen Docker
      run: docker run docker.io/library/imagengerald:v1.0
      continue-on-error: true
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@v0.36.0
      with: 
        image-ref: 'docker.io/library/imagengerald:v1.0'
        severity: 'CRITICAL,HIGH'

  security:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Aqua Security Trivy
        run: echo 'Hola Mundo'
    
